name: titgram
description: "Titgram"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  go_router: ^13.2.0
  google_mobile_ads: ^4.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.1
  permission_handler: ^11.3.0
  transparent_image: ^2.0.1
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
